blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.com/invite/FQ7jmGBd6c
    about: Please ask questions and discuss ideas in our Discord server before opening a generic issue.
  - name: ðŸ“– Documentation
    url: https://eternalcode.pl/docs/eternalcore/introduction
    about: Read the documentation to see if your question is already answered.
